/**
 * 慧源黑飞协议飞机类型类，用于定义各种黑飞协议飞机的类型常量
 */
export class HyDroneCode {
  /**
   * 黑飞
   */
  public static readonly FX: string = "FX";

  /**
   * 志崇单镜头
   */
  public static readonly ZCZ110FX: string = "ZCZ110FX";

  /**
   * 志崇双镜头
   */
  public static readonly ZCZ210FX: string = "ZCZ210FX";

  /**
   * 志崇01  双镜头
   */
  public static readonly ZC001R0P: string = "ZC001R0P";

  /**
   * 志崇 新 宝宏林工
   */
  public static readonly ZC0001FX: string = "ZC0001FX";

  /**
   * 连煌单镜头
   */
  public static readonly TQM1RQFX: string = "TQM1RQFX";

  /**
   * 连煌无刷单镜头
   */
  public static readonly TQM1RUFX: string = "TQM1RUFX";

  /**
   * 连煌
   */
  public static readonly HC7581HM: string = "HC7581HM";

  /**
   * 连煌
   */
  public static readonly HC7590FX: string = "HC7590FX";

  /**
   * 连煌
   */
  public static readonly HC775VFX: string = "HC775VFX";

  /**
   * 连煌
   */
  public static readonly HC782VFX: string = "HC782VFX";

  /**
   * 连煌双镜头
   */
  public static readonly TQP1RQFX: string = "TQP1RQFX";

  /**
   * 速铭双镜头
   */
  public static readonly SM1902FX: string = "SM1902FX";

  /**
   * 疆域 1
   */
  public static readonly TXJLGCX0: string = "TXJLGCX0";

  /**
   * 疆域 2
   */
  public static readonly TXJLGD50: string = "TXJLGD50";

  /**
   * 疆域 3
   */
  public static readonly TXJLGDG0: string = "TXJLGDG0";

  /**
   * 飞力特（带我们的云台）
   */
  public static readonly FT851SFX: string = "FT851SFX";

  /**
   * 富莱鹰
   */
  public static readonly TQZ10ZFX: string = "TQZ10ZFX";

  /**
   * 富莱鹰
   */
  public static readonly FLYLGCO0: string = "FLYLGCO0";

  /**
   * 天驱
   */
  public static readonly TQK3RXFX: string = "TQK3RXFX";

  /**
   * 天驱
   */
  public static readonly TQK3RZFX: string = "TQK3RZFX";

  /**
   * 天驱
   */
  public static readonly TQK3RCFX: string = "TQK3RCFX";

  /**
   * 天驱-避障
   */
  public static readonly TQK3RBFX: string = "TQK3RBFX";

  /**
   * 君亿
   */
  public static readonly JYEX5XFX: string = "JYEX5XFX";

  /**
   * 君亿-中继版本，飞行距离不做处理
   */
  public static readonly JYEX5DFX: string = "JYEX5DFX";

  /**
   * 君亿
   */
  public static readonly JY531VFX: string = "JY531VFX";

  /**
   * 杜威
   */
  public static readonly DW0001FX: string = "DW0001FX";

  /**
   * 杜威
   */
  public static readonly DW0132FX: string = "DW0132FX";

  /**
   * 立煌
   */
  public static readonly LH0001FX: string = "LH0001FX";

  /**
   * 立煌
   */
  public static readonly LH0002FX: string = "LH0002FX";

  /**
   * 协宇
   */
  public static readonly XY0001FX: string = "XY0001FX";

  /**
   * 协宇
   */
  public static readonly XY1001FX: string = "XY1001FX";

  /**
   * 胖胖-双镜头
   */
  public static readonly PP0001FX: string = "PP0001FX";

  /**
   * 胖胖-云台
   */
  public static readonly PP0002FX: string = "PP0002FX";

  /**
   * 胖胖
   */
  public static readonly PP0003FX: string = "PP0003FX";

  /**
   * 胖胖
   */
  public static readonly PPHH10FX: string = "PPHH10FX";

  /**
   * 胖胖高度500/8c除10
   */
  public static readonly PP0005FX: string = "PP0005FX";

  /**
   * 胖胖高度500/8c除10
   */
  public static readonly PP0010FX: string = "PP0010FX";

  /**
   * 胖胖
   */
  public static readonly SH001NT1: string = "SH001NT1";

  /**
   * 胖胖二轴
   */
  public static readonly PP23YTFX: string = "PP23YTFX";

  /**
   * 胖胖三轴
   */
  public static readonly PP0026FX: string = "PP0026FX";

  /**
   * 毅恒
   */
  public static readonly YH0001FX: string = "YH0001FX";

  /**
   * 优迪
   */
  public static readonly U39003FX: string = "U39003FX";

  /**
   * 骁葛
   */
  public static readonly XG0001FX: string = "XG0001FX";

  /**
   * 辉科-黑飞
   */
  public static readonly FX30P3FX: string = "FX30P3FX";

  /**
   * 辉科-宝宏林工
   */
  public static readonly HKX09PFX: string = "HKX09PFX";

  /**
   * 雅德
   */
  public static readonly YDXT01FX: string = "YDXT01FX";

  /**
   * 博洋
   */
  public static readonly LIU001FX: string = "LIU001FX";

  /**
   * 博洋
   */
  public static readonly LIUB61FX: string = "LIUB61FX";

  /**
   * 博洋
   */
  public static readonly CBY0B2FX:string = "BY0B2FX";
  /**
   * 博洋无系统屏
   */
  public static readonly CBYZB2FX:string = "CBYZB2FX";

  /**
   * 博洋
   */
  public  static readonly  LIUB93FX :string= "LIUB93FX";

  /**
   * 博洋-欣亿斯
   */
  public static readonly BYX2A0FX: string = "BYX2A0FX";

  /**
   * 华彩
   */
  public static readonly HC780VFX: string = "HC780VFX";

  /**
   * 华彩
   */
  public static readonly HC775BFX: string = "HC775BFX";

  /**
   * 华彩
   */
  public static readonly KY7573FX: string = "KY7573FX";

  public static readonly HC7577FX: string = "HC7577FX";

  /**
   * 华彩
   */
  public static readonly KY7913FX: string = "KY7913FX";

  /**
   * 育星
   */
  public static readonly OR0181FX: string = "OR0181FX";

  /**
   * 育星
   */
  public static readonly XYZ091FX: string = "XYZ091FX";

  /**
   * 小明科技
   */
  public static readonly XMM011FX: string = "XMM011FX";

  /**
   * 小明科技
   */
  public static readonly XMM010FX: string = "XMM010FX";

  /**
   * 小明科技
   */
  public static readonly XMM012FX: string = "XMM012FX";

  /**
   * 欣亿斯
   */
  public static readonly XYS001FX: string = "XYS001FX";

  /**
   * 添翼
   */
  public static readonly HX518XFX: string = "HX518XFX";

  /**
   * 联飞
   */
  public static readonly CFEX5XFX: string = "CFEX5XFX";

  /**
   * 高兔
   */
  public static readonly TXDG9XFX: string = "TXDG9XFX";

  /**
   * 宝宏胖胖
   */
  public static readonly PPHH12FX: string = "PPHH12FX";
  /**
   * 宝宏胖胖
   */
  public static readonly PPHH13FX:string = "PPHH13FX";
  /**
   * 博洋活石
   */
  public static readonly LIHSB9FX:string = "LIHSB9FX";
  /**
   * 趣贝
   */
  public static readonly QNTQ01FX:string = "QNTQ01FX";


  /**
   * 判断是否为黑飞协议
   * 
   * @returns 是否为黑飞协议
   */
  public static isFx(): boolean {
    // 注意：这里需要根据实际情况实现，暂时返回false
    return false;
  }
}