/**
 * 功能类型枚举
 * 对应无人机的各种功能类型
 */
export enum MoreType {
  /**
   * 镜头翻转
   */
  REV = 0,
  
  /**
   * 3D模式
   */
  _3D = 1,
  
  /**
   * 多点飞行
   */
  POINT = 2,
  
  /**
   * 跟随
   */
  FOLLOW = 3,
  
  /**
   * 环绕
   */
  AROUND = 4,
  
  /**
   * 手势拍照
   */
  GESTURE = 5,
  
  /**
   * 解锁按钮
   */
  UNLOCK = 6,
  
  /**
   * 摇杆
   */
  ROCKER = 7,
  
  /**
   * 切换镜头
   */
  SWITCH_CAMERA = 8,
  
  /**
   * 找飞机
   */
  FIND_DRONE = 9,
  
  /**
   * 镜头调节
   */
  CAMERA_ADJUST = 10,
  
  /**
   * 速度控制
   */
  SPEED = 11,
  
  /**
   * 音乐
   */
  MUSIC = 12,
  
  /**
   * 云台调节
   */
  PTZ = 13,
  
  /**
   * 一键远飞
   */
  FAR = 14,
  
  /**
   * GPS模式/室内模式切换
   */
  GPS_OFF = 15,
  
  /**
   * 无头模式
   */
  HEADLESS = 16,
  
  /**
   * 避障
   */
  OBSTACLE = 17,
  
  /**
   * 视觉（单目）避障
   */
  VISION_OBSTACLE = 18,
  
  /**
   * 一键远飞
   */
  FAR_FLY = 19,
  
  /**
   * 冲天功能变高
   */
  SKY_FLY = 20,
  
  /**
   * 螺旋功能变高
   */
  SPIRAL_FLY = 21,
  
  /**
   * 运动模式
   */
  SPORT = 21,
  
  /**
   * 图像跟随
   */
  FOLLOW_TRACK = 22,
  
  /**
   * 巡航
   */
  CRUISE = 23,
  
  /**
   * 预览方向
   */
  PREVIEW_DIRECTION = 24,
  
  /**
   * 投放
   */
  PLACE = 25
}



